export const ELEMENTIDS = {
  // ID Selectors
  OVERLAY: "#overlay",
  LOADING_DIV: "#loading-div",
  RESTART_DIV: "#restart-div",
  SQUARE_FRAME: "#square-frame",
  SECTION_WORD_LIST: "#section-word-list",
  SETTING_FORM: "#setting-form",
  WORD_COUNT_INPUT: "#range-word-count",
  WORD_COUNT_DISPLAY: "#label-word-count",
  MAX_LENGTH_INPUT: "#range-max-length",
  MAX_LENGTH_DISPLAY: "#label-max-length",
  COUNTDOWN_INPUT: "#range-countdown",
  COUNTDOWN_DISPLAY: "#label-countdown",
  OFFCANVAS_ELEMENT: "#offcanvasNavbar",
  RELOAD_BTN: "#btn-reload",
  COUNTDOWN_CONTAINER: "#countdown-container",
  COUNTDOWN: "#countdown",
  RESTART_MSG: "#restart-message",
};